BUEnrolment/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BUEnrolment.Models;
using System.Web.Security;
using WebMatrix.WebData;

namespace BUEnrolment.Controllers
{
    public class RequestController : Controller
    {
        private BUEnrolmentContext db = new BUEnrolmentContext();

        //
        // GET: /Request/

        [Authorize(Roles = "Admin, Student")]
        public ActionResult Index()
        {
            List<Student> StudentList = new List<Student>();
            if (Roles.IsUserInRole("Admin"))
            {
                StudentList = db.Students.Where(s => s.Requests.Any(r => r.Status == "Pending")).Include(s => s.Requests.Select(r => r.Subject)).ToList();
            }
            else if (Roles.IsUserInRole("Student"))
            {
                Student student = db.Students.
                Include(m => m.Requests).
                Include(m => m.Requests.Select(r => r.Subject)).
                FirstOrDefault(s => s.Id == WebSecurity.CurrentUserId);
                StudentList.Add(student);
            }
            ViewBag.Students = StudentList;
            return View();
        }

        //
        // GET: /Request/Create
        [Authorize(Roles = "Admin, Student")]
        public ActionResult Create()
        {
            Student student = db.Students.Include(s => s.EnrolledSubjects).FirstOrDefault(s => s.Id == WebSecurity.CurrentUserId);

            ViewBag.RequestableSubjects = new SelectList(student.GetRequestableSubjects(db.Subjects.Where(s => s.Active).ToList()), "Id", "Name");
            ViewBag.CurrentStudent = student;
            return View();
        }

        // 
        // POST: /Request/Create
        [Authorize(Roles = "Admin, Student")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Request request, int? selectedSubject)
        {
            if (selectedSubject == null)
            {
                ModelState.AddModelError(string.Empty, "No subject was selected");
            }

            if (ModelState.IsValid)
            {
                Student currentStudent = db.Students.FirstOrDefault(s => s.Id == WebSecurity.CurrentUserId);
                Subject subject = db.Subjects.FirstOrDefault(s => s.Id == selectedSubject);

                // user not logged in or not found
                if (currentStudent == null)
                {
                    return RedirectToAction("Index");
                }

                request.Subject = subject;
                request.Status = "Pending";
                db.Entry(currentStudent).State = EntityState.Modified;
                db.Entry(currentStudent).Collection(m => m.Requests).Load();

                // check if the student has already made request for the same subject
                if (currentStudent.Requests.All(r => r.Subject.Id != selectedSubject))
                {
                    currentStudent.Requests.Add(request);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "You have previously made a request for this subject already.");
                }
            }

            Student student = db.Students.Include(s => s.EnrolledSubjects).FirstOrDefault(s => s.Id == WebSecurity.CurrentUserId);
            ViewBag.RequestableSubjects = new SelectList(student.GetRequestableSubjects(db.Subjects.Where(s => s.Active).ToList()), "requestId", "Name");
            ViewBag.CurrentStudent = student;

            return View(request);
        }

        [Authorize(Roles = "Admin, Student")]
        public ActionResult Approve(int requestId, int studentId)
        {
            Request request = db.Requests.Include(r => r.Subject).FirstOrDefault(r => r.Id == requestId);
            request.Status = "Approve";
            db.Entry(request).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Enrol", "Student", new { studentId = studentId, subjectId = request.Subject.Id });
        }

        [Authorize(Roles = "Admin, Student")]
        public ActionResult Disapprove(int requestId, int studentId)
        {
            Request request = db.Requests.Include(r => r.Subject).FirstOrDefault(r => r.Id == requestId);
            request.Status = "Disapprove";
            db.Entry(request).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BUEnrolment/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BUEnrolment.Models;
using System.Web.Security;
using WebMatrix.WebData;

namespace BUEnrolment.Controllers
{
    /// <summary>
    /// Handle Result related pages
    /// </summary>
    public class ResultController : Controller
    {
        /// <summary>
        /// Database context for EntityFramework
        /// </summary>
        public BUEnrolmentContext db = new BUEnrolmentContext();

        public ResultController(ref BUEnrolmentContext db)
        {
            AppDomain.CurrentDomain.SetData("DataDirectory", System.IO.Directory.GetCurrentDirectory());
            this.db = db;
        }

        public ResultController()
        {

        }


        /// <summary>
        /// GET: /Result/Create
        /// Enter result for subject page
        /// </summary>
        /// <param name="id">subject id</param>
        /// <returns></returns>
        public ActionResult Create(int id)
        {
            Subject subject = db.Subjects.Include(s => s.EnrolledStudents)
                .Include(s => s.EnrolledStudents.Select(e => e.CompletedSubject))
                .FirstOrDefault(s => s.Id == id);
            ViewBag.subject = subject;

            return View();
        }

        /// <summary>
        /// POST: /Result/Create
        /// Handler for Result entry
        /// </summary>
        /// <param name="results">list of entered results</param>
        /// <param name="id">subject id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(List<Result> results, int id)
        {
            if (ModelState.IsValid)
            {
                Subject subject = db.Subjects.Include(s => s.EnrolledStudents).FirstOrDefault(s => s.Id == id);

                for (int i = 0; i < subject.EnrolledStudents.Count; i++)
                {
                    if (results[i].Mark != null)
                    {
                        results[i].Subject = subject;
                        subject.EnrolledStudents[i].CompleteSubject(results[i]);
                        subject.EnrolledStudents.Remove(subject.EnrolledStudents[i]);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Create");
            }
            else
            {
                Subject subject = db.Subjects.Include(s => s.EnrolledStudents)
                    .Include(s => s.EnrolledStudents.Select(e => e.CompletedSubject))
                    .FirstOrDefault(s => s.Id == id);
                ViewBag.subject = subject;
            }

            return View(results);
        }

        /// <summary>
        /// GET: /Result/Details
        /// 
        /// List result page for the current logged in student
        /// </summary>
        /// <returns></returns>
        public ActionResult Details()
        {
            Student student = db.Students.Include(s => s.CompletedSubject).Include(s => s.CompletedSubject.Select(c => c.Subject)).FirstOrDefault(s => s.Id == WebSecurity.CurrentUserId);
            return View(student.CompletedSubject);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BUEnrolment/Views/Shared/SiteLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/Style.css")" />
    <script src="@Url.Content("~/Content/js/script.js")" type="text/javascript"></script>
</head>
<body class="@((WebSecurity.IsAuthenticated) ? "authenticated" : "not-authenticated")">
    <div id="container">
        <div id="header_bg">
            <div id="header">
                <h1>Broadway University</h1>
                <h2>Student Enrolment System</h2>
            </div>
        </div>
            <div id="main" class="clearfix">
                <div id="leftmenu">
                    <ul>
                    @if(Roles.IsUserInRole("Admin"))
                    {           
                        <li>@Html.ActionLink("Manage Subjects","Index", "Subject", null, null)</li>
                        <li>@Html.ActionLink("View Requests","Index", "Request", null, null)</li>
                    }
                    else if(Roles.IsUserInRole("Student"))
                    {
                        <li>@Html.ActionLink("Enrolled Subjects","Enrolled", "Subject", null, null)</li>
                        <li>@Html.ActionLink("Enrol","Index", "Subject", null, null)</li>
                        <li>@Html.ActionLink("Create Requests","Create", "Request", null, null)</li>
                        <li>@Html.ActionLink("View Requests","Index", "Request", null, null)</li>
                        <li>@Html.ActionLink("View Results","Details", "Result", null, null)</li>
                    }
                    @if(WebSecurity.IsAuthenticated) {
                        <li>
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="submit" value="Logout" class="link" />
                            }
                        </li>
                    }
                    </ul>
                </div>

            <div id="content">
                <div id="content_main">
                    @RenderBody()
                </div>
            </div>

        </div>
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>